// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'dotted_border_builder.dart';

// **************************************************************************
// Generator: JsonWidgetLibraryBuilder
// **************************************************************************

// ignore_for_file: avoid_init_to_null
// ignore_for_file: deprecated_member_use

// ignore_for_file: prefer_const_constructors
// ignore_for_file: prefer_const_constructors_in_immutables
// ignore_for_file: prefer_final_locals
// ignore_for_file: prefer_if_null_operators
// ignore_for_file: prefer_single_quotes
// ignore_for_file: unused_local_variable

class DottedBorderBuilder extends _DottedBorderBuilder {
  const DottedBorderBuilder({required super.args});

  static const kType = 'dotted_border';

  /// Constant that can be referenced for the builder's type.
  @override
  String get type => kType;

  /// Static function that is capable of decoding the widget from a dynamic JSON
  /// or YAML set of values.
  static DottedBorderBuilder fromDynamic(
    dynamic map, {
    JsonWidgetRegistry? registry,
  }) => DottedBorderBuilder(args: map);

  @override
  DottedBorderBuilderModel createModel({
    ChildWidgetBuilder? childBuilder,
    required JsonWidgetData data,
  }) {
    final model = DottedBorderBuilderModel.fromDynamic(
      args,
      registry: data.jsonWidgetRegistry,
    );

    return model;
  }

  @override
  DottedBorder buildCustom({
    ChildWidgetBuilder? childBuilder,
    required BuildContext context,
    required JsonWidgetData data,
    Key? key,
  }) {
    final model = createModel(childBuilder: childBuilder, data: data);

    return DottedBorder(
      animation: model.animation,
      childOnTop: model.childOnTop,
      ignoring: model.ignoring,
      key: key,
      options: model.options,
      child: model.child.build(childBuilder: childBuilder, context: context),
    );
  }
}

class JsonDottedBorder extends JsonWidgetData {
  JsonDottedBorder({
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
    this.animation,
    this.childOnTop = true,
    this.ignoring = true,
    this.options = const RectDottedBorderOptions(),
    required this.child,
  }) : super(
         jsonWidgetArgs: DottedBorderBuilderModel.fromDynamic(
           {
             'animation': animation,
             'childOnTop': childOnTop,
             'ignoring': ignoring,
             'options': options,
             'child': child,

             ...args,
           },
           args: args,
           registry: registry,
         ),
         jsonWidgetBuilder: () => DottedBorderBuilder(
           args: DottedBorderBuilderModel.fromDynamic(
             {
               'animation': animation,
               'childOnTop': childOnTop,
               'ignoring': ignoring,
               'options': options,
               'child': child,

               ...args,
             },
             args: args,
             registry: registry,
           ),
         ),
         jsonWidgetType: DottedBorderBuilder.kType,
       );

  /* AUTOGENERATED FROM [DottedBorder.animation]*/
  /// The animation for the dotted border.
  final Animation<double>? animation;

  /* AUTOGENERATED FROM [DottedBorder.childOnTop]*/
  /// Wether to paint the child on top of the border.
  final bool childOnTop;

  /* AUTOGENERATED FROM [DottedBorder.ignoring]*/
  /// Whether the border should ignore pointer events.
  final bool ignoring;

  /* AUTOGENERATED FROM [DottedBorder.options]*/
  /// The dotted border options.
  final DottedBorderOptions options;

  /* AUTOGENERATED FROM [DottedBorder.child]*/
  /// The widget below this widget in the tree.
  final JsonWidgetData child;
}

class DottedBorderBuilderModel extends JsonWidgetBuilderModel {
  const DottedBorderBuilderModel(
    super.args, {
    this.animation,
    this.childOnTop = true,
    this.ignoring = true,
    this.options = const RectDottedBorderOptions(),
    required this.child,
  });

  /* AUTOGENERATED FROM [DottedBorder.animation]*/
  /// The animation for the dotted border.
  final Animation<double>? animation;

  /* AUTOGENERATED FROM [DottedBorder.childOnTop]*/
  /// Wether to paint the child on top of the border.
  final bool childOnTop;

  /* AUTOGENERATED FROM [DottedBorder.ignoring]*/
  /// Whether the border should ignore pointer events.
  final bool ignoring;

  /* AUTOGENERATED FROM [DottedBorder.options]*/
  /// The dotted border options.
  final DottedBorderOptions options;

  /* AUTOGENERATED FROM [DottedBorder.child]*/
  /// The widget below this widget in the tree.
  final JsonWidgetData child;

  static DottedBorderBuilderModel fromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    final result = maybeFromDynamic(map, args: args, registry: registry);

    if (result == null) {
      throw Exception(
        '[DottedBorderBuilder]: requested to parse from dynamic, but the input is null.',
      );
    }

    return result;
  }

  static DottedBorderBuilderModel? maybeFromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    DottedBorderBuilderModel? result;

    if (map != null) {
      if (map is String) {
        map = yaon.parse(map, normalize: true);
      }

      if (map is DottedBorderBuilderModel) {
        result = map;
      } else {
        registry ??= JsonWidgetRegistry.instance;
        map = registry.processArgs(map, <String>{}).value;
        result = DottedBorderBuilderModel(
          args,
          animation: map['animation'],
          childOnTop: JsonClass.parseBool(map['childOnTop'], whenNull: true),
          ignoring: JsonClass.parseBool(map['ignoring'], whenNull: true),
          options: map['options'] ?? const RectDottedBorderOptions(),
          child: () {
            dynamic parsed = JsonWidgetData.fromDynamic(
              map['child'],
              registry: registry,
            );

            if (parsed == null) {
              throw Exception(
                'Null value encountered for required parameter: [child].',
              );
            }
            return parsed;
          }(),
        );
      }
    }

    return result;
  }

  @override
  Map<String, dynamic> toJson() {
    return JsonClass.removeNull({
      'animation': animation,
      'childOnTop': true == childOnTop ? null : childOnTop,
      'ignoring': true == ignoring ? null : ignoring,
      'options': const RectDottedBorderOptions() == options ? null : options,
      'child': child.toJson(),

      ...args,
    });
  }
}

class DottedBorderSchema {
  static const id =
      'https://peiffer-innovations.github.io/flutter_json_schemas/schemas/json_dynamic_widget_example/dotted_border.json';

  static final schema = <String, Object>{
    r'$schema': 'http://json-schema.org/draft-07/schema#',
    r'$id': id,
    'title': 'DottedBorder',
    'type': 'object',
    'additionalProperties': false,
    'properties': {
      'animation': SchemaHelper.anySchema,
      'childOnTop': SchemaHelper.boolSchema,
      'ignoring': SchemaHelper.boolSchema,
      'options': SchemaHelper.anySchema,
      'child': SchemaHelper.objectSchema(JsonWidgetDataSchema.id),
    },
  };
}
